### ISSUE TITLE
Generated nix-file does not build on macOS

### ISSUE THREAD

**Issue by mbrasch** [nix-community/nix-init#116]
I am trying to build an older version of vault (1.4.3) using nix-init. However, the nix file created does not build on macOS (13.3.1, aarch64):

> vendor/github.com/shirou/gopsutil/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]

During my research I came across this issue:

> This is because LLVM/Clang 11 automatically adds -Werror,-Wundef-prefix=TARGET_OS_ as default compiler arguments and apparently TARGET_OS_MAC isn't defined in this compilation environment.
>
> [...]
>
> I can work around this by adding #cgo CFLAGS: -Wno-undef-prefix or #include <TargetConditionals.h> to the failing import "C" comment. The latter is likely more robust and seemingly indicates that TargetConditions.h isn't being included by another #include in this block.
>
> -- https://github.com/shirou/gopsutil/issues/976

Is there a possibility that nix-init detects and fixes this problem itself? Or do I always have to adapt the files myself?

**Comment by figsoda** [comment]
This is to be expected. nix-init doesn't guarantee that the generated file works, you would have to adapt the files yourself for now.

> Is there a possibility that nix-init detects and fixes this problem itself?

Not in this specific case, though ideally nix-init would be able to recognize gopsutil and apply the changes needed. I will look into that and go dependencies overall.

There are plans to make nix-init try to build the package and find missing dependencies: https://github.com/RaitoBezarius/buildxyz/issues/8, but it wouldn't help in this specific case.

**Comment by mbrasch** [comment]
I am ready for testing. :)

**Comment by figsoda** [comment]
Could you take a look at #174?
